---
title: "3panelsankey"
author: "Sydney Shimizu"
format: html
editor: visual
---

```{r}

# Obtaining Values for Sankey Plot

heart3<-read.csv("C:/Users/12063/Downloads/heart3.csv")

# 1) Count of Statuses Escalating

table(heart3$first_status)

# S3:802, S4:2052, S6:1463

# Note: There are 46 missing values for first status
# Note: There were 3 patients who downgraded from 1->2

# 2) Stable vs. Escalated

table(heart3$group)

# Stable:5512, Escalated:4366

# 3) Event Count

table (heart3$event)

# Death:96, Transplant:7256, Recovery:2, Downgrade:698, Upgrade:595, Censored:41, Delist:1190

```

```{r}

# Loading essential libraries

library(networkD3)
library(htmlwidgets)

# Creating nodes data frame

nodes<-data.frame(name=c("Status 3 Patients (802)","Status 4 Patients (2052)","Status 6 Patients (1463)","Stable Status 2 Patients (5512)","Patients who Escalated to Status 2 (4366)","Status 2 Patients (9878)","Patients who Received a Transplant (7256)","Delisted Patients (1190)","Patients who Downgraded (698)","Patients who Upgraded (595)", "Patients who Died (96)", "Censored Patients (41)", "Patients who Recovered (2)"),
                  group=c("escalated","escalated","escalated","stable","escalated","status 2","transplant","delist","downgrade","upgrade","died","censored","recovered"))

# Creating the links data frame 
links<-data.frame(source=c(0,1,2,3,4,5,5,5,5,5,5,5),
                  target=c(4,4,4,5,5,6,7,8,9,10,11,12),
                  value=c(802,2052,1463,5512,4366,7256,1190,698,595,96,41,2),
                  group=c("escalated","escalated","escalated","stable","escalated","transplant","delist","downgrade","upgrade","died","censored","recovered"))

# Adding Color Scheme

my_color <- 'd3.scaleOrdinal()
  .domain(["escalated", "stable","status 2", "transplant", "delist", "downgrade","upgrade","died","censored","recovered"])
  .range(["#9ACD32", "#FFEC8B","#87CEFF", "#EEAEEE", "#4876FF","#FF8247","#EE0000","#8B8682","#FFB5C5"])'

# Creating the Sankey Plot

sankeyPlotWeb <- sankeyNetwork(Links = links, Nodes = nodes,
Source = "source", Target = "target",
Value = "value", NodeID = "name", NodeGroup="group", LinkGroup="group",colourScale=my_color,
units = "Patients", fontSize = 14, fontFamily = "Helvetica Neue, Helvetica, Arial, sans-serif",nodeWidth = 30)


# Save the plot as an HTML file
saveWidget(sankeyPlotWeb, file = "C:/Users/12063/Documents/Programming in R/LAsBEST/sankey_plot.html")
```
