---
title: "Heart Transplant Project - LA's BeST 2026"
author: "Jesus Rodriguez, Sydney Shimizu, Julia Aptekar"
format: html
---

```{r setup,  output = F, message = F, warning= F}
library(tidyverse) # general tidying and manipulation
library(readxl) # reading xlsx files
library(kableExtra) # nice tables
library(lubridate) # easier working with dates
```

# Loading in Data

```{r, output = F, message = F, warning= F}
heart_data <- read_csv("data/LAsBEST26_SUBSET.csv", col_select = -1)

# if needed here is the data dictionary
data_dictionary <- read_xlsx("data/STAR Files Data Dictionary.xlsx", skip = 1, sheet = 6)
data_dictionary <- read_xlsx("data/STAR Files Data Dictionary.xlsx", skip = 1, sheet = 1)

# note <- read_xlsx("data/STAR Files Data Dictionary.xlsx", n_max = 1, col_names = F)
```

# Data Cleaning

```{r}
# Checking structure
str(heart_data)

# Checking to see spread of certain variables to see if they are categorical or not
heart_data %>% 
  count(UNOS_CAND_STAT_CD)

heart_data %>% 
  count(REM_CD_NEW)

heart_data %>% 
  count(FTIME)

names(heart_data)
```
Formatting columns

```{r}
heart_data <- 
  heart_data %>%
  mutate(
    across(
      c(WL_ID_CODE, #ID
        WLREG_AUDIT_ID_CODE, #ID 
        UNOS_CAND_STAT_CD_WAITLIST, 
        UNOS_CAND_STAT_CD, EXCEPTION, 
        REM_CD_NEW, 
        FSTATUS, 
        GENDER, 
        ETHCAT, 
        BTYPE_REC, 
        DIAB),
      as.factor
    ),
    across(
      c(FTIME, 
        INIT_BMI_NEW, 
        INIT_AGE),
      as.numeric
    ),
    across(
      c(INIT_DATE,
        CHG_DATE,
        END_DATE_NEW
      ),
      as_date
    )
  )
  
```

# Using a landmark date of 7 days, define two groups

```{r}
heart_data <- 
  heart_data %>% 
  mutate(
    landmark_date = 
      INIT_DATE + weeks(1)
  )
  
```

## Defining "Stable"

Individuals who were listed at status 2 and were status 2 at day 7

```{r}

heart_data %>% 
  mutate(
    STATUS = 
      if_else(
        
      )
  )

```

